include: "rules/common.smk"

rule all:
    input:
        get_final_output()

include: "rules/fileconversion.smk",
include: "rules/preprocessing.smk",
include: "rules/requantification.smk",
include: "rules/GNPSexport.smk",
include: "rules/sirius_csi.smk",
include: "rules/sirius.smk",
include: "rules/spectralmatcher.smk",
include: "rules/analogsearch.smk",
include: "rules/fbmn_integration.smk"