include: "rules/common.smk"

rule all:
    input:
        get_final_output()

include: "rules/fileconversion.smk",
include: "rules/preprocessing.smk",
include: "rules/requantification.smk",
include: "rules/GNPS_export.smk",
include: "rules/SIRIUS.smk",
include: "rules/spectralmatcher.smk",
include: "rules/MS2Query.smk",
include: "rules/fbmn_integration.smk"